### ISSUE TITLE
[issue]: The name of chat history should be save into the db

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/rebel#38]
We should invoke this API to save/update session name. However, if we change the session tab or create new session while the streaming response in the process. The save or update will failed. See the issues with bug labels.

So, when we should save the first question[:20] as session name is important. I think we can save it after user input the question rather than save it after all the stream finished.

![Screenshot 2024-07-14 at 5 32 34 PM](https://github.com/user-attachments/assets/9c7a7e7e-19e2-483c-94c3-beb93a4f78d8)

**Comment by cbh778899** [comment]
fixed by #40
